version: '3.3'
services:
  redis-container:
    image: redis:alpine
    container_name: oegaein-redis
    command: redis-server --port 6379 --requirepass ${input_redis_password}
    hostname: redis
    ports:
      - "6379:6379"

  rabbitmq-container:
    image: pcloud/rabbitmq-stomp
    container_name: oegaein-rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: ${input_user_name}
      RABBITMQ_DEFAULT_PASS: ${input_rabbitmq_password}