spring:
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    expire: 60
  data:
    mongodb:
      host: localhost
      port: 27017
      database: testdb
  datasource:
    url: jdbc:mysql://localhost:3306/oegaein?&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&rewriteBatchedStatements=true
    username: root
    password: tjfgmlrhks9478@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
      show_sql: true
      default_batch_fetch_size: 100
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.jdbc: debug